sudo: false

language: node_js

node_js:
  - "11"
  - "10"

cache:
  directories:
    - node_modules

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
